# BACKEND팀 파드들(web, srv, db)
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: web
    team: backend
  name: pod-be-1
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-be-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: srv
    team: backend
  name: pod-be-2
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-be-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: db
    team: backend
  name: pod-be-3
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-be-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
  volumes:
  - name: html
    