# frontend팀 파드들(web, srv, db)
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: web
    team: frontend
  name: pod-fe-1
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-fe-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: srv
    team: frontend
  name: pod-fe-2
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-fe-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: db
    team: frontend
  name: pod-fe-3
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-fe-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---