# DBA팀 파드들(web, srv, db)
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: web
    team: dba
  name: pod-dba-1
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-dba-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: srv
    team: dba
  name: pod-dba-2
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-dba-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: sb
    team: dba
  name: pod-dba-3
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-dba-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}