apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: se-svc
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  selector:
    team: se
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: dba-svc
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 80
    nodePort: 30082
  selector:
    team: dba
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend-svc
spec:
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 80
    nodePort: 30083
  selector:
    team: frontend
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: backend-svc
spec:
  type: NodePort
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 80
    nodePort: 30084
  selector:
    team: backend
status:
  loadBalancer: {}
---