apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-web
  name: pod-web
spec:
  containers:
    - name: pod-web
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pod-vol
          mountPath: /usr/share/nginx/html

  volumes:
  - name: pod-vol
    hostPath:
      path: /home/pista/pub
      type: DirectoryOrCreate # 경로가 없으면 생성하도록 지정