apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: web
    type: infra
  name: pod-label-1
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: srv
    type: infra
  name: pod-label-2
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: db
    type: infra
  name: pod-label-3
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: web
    type: dev
  name: pod-label-4
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-4
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: srv
    type: dev
  name: pod-label-5
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    job: db
    type: dev
  name: pod-label-6
spec:
  containers:
  - image: nginx:1.29.4-alpine
    name: pod-label-6
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}