apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: front-web-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    job: web
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: infra-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 80
  selector:
    type: infra 
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: infra-web-svc
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 80
  selector:
    job: web
    type: infra
status:
  loadBalancer: {}