apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
  name: svc-deploy-web
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
  selector:
    app: deploy-web
  type: NodePort
status:
  loadBalancer: {}
