apiVersion: v1
kind: Pod
metadata:
  name: pod-client
  labels:
    run: pod-client
spec:
  containers:
    - name: myapp
      image: nginx:latest
      volumeMounts:                    
        - name: html-app
          mountPath: /usr/share/nginx/html
    - name: sidecar
      image: curlimages/curl:8.5.0
      volumeMounts:
        - name: html-app
          mountPath: /html-log
      args: ["/bin/sh","-c","curl https://www.kyobobook.co.kr/ > /html-log/index.html; sleep 3600"]
  volumes: 
    - name: html-app
      emptyDir: {}