apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pista-ip-pool
  namespace: metallb-system
spec:
    addresses:
    - 192.168.5.101 - 192.168.5.110
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pista-ip-pool
  namespace: metallb-system
spec:
    addresses:
    - 192.168.5.101 - 192.168.5.110