apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-1
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      volumeMounts:
        - name: pod-vol
          mountPath: /usr/share/nginx/html
  volumes:
  - name: pod-vol
    persistentVolumeClaim:
      claimName: pvc-1