#RWO ReadWriteOnce 단 하나의 노드에서만 읽기/쓰기 
#ROX ReadOnlyMany 여러 노드에서 읽기 전용
#RWX ReadWriteMany 여러 노드에서 읽기/쓰기
#RWOP ReadWriteOncePod 단일 Pod에서만 읽기/쓰기


apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 1Gi            # (권장) 1G보다는 1Gi(기비바이트) 표준
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage # (권장) PV/PVC 매칭을 위해 클래스 이름 지정 추천
  local:
    path: /DATA1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-n1]}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
spec:
  capacity:
    storage: 2Gi            # (권장) 1G보다는 1Gi(기비바이트) 표준
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage # (권장) PV/PVC 매칭을 위해 클래스 이름 지정 추천
  local:
    path: /DATA1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-n2]}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
spec:
  capacity:
    storage: 3Gi            # (권장) 1G보다는 1Gi(기비바이트) 표준
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage # (권장) PV/PVC 매칭을 위해 클래스 이름 지정 추천
  local:
    path: /DATA1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-n3]}
