apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: gition
spec:
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-master
  namespace: gition
subsets:
  - addresses:
      - ip: 172.100.100.11
    ports:
      - port: 3306